### ISSUE TITLE
Automate manual steps in ray workflow

### ISSUE THREAD

**Issue by julietcohen** [PermafrostDiscoveryGateway/viz-workflow#16]
* PDG Workflow version: Ray
* Python version: 3.9
* Server: Delta

## Ways to automate the ray workflow:

- [x] **1. create requirements file for users to easily create new python environment to run entire workflow from start to finish, OR within script to activate environment include hard-coded file path to a pre-made conda environment that lives in neutral place (scratch dir) so any user is activating the same environment instead of making one for themselves, OR bash commands within script that install all 3 local packages and other non-local packages after the user manually switches into new empty environment**
  - packages to include in environment:
    - `viz-staging` (pip)
    - `viz-raster` (pip)
    - `viz-3dtiles` (pip)
    - `ray` (pip)
    - `glances` (conda)
  - to discuss if we want to pursue the requirements file route (instead of a hard-coded path to a pre-made conda environment in the `scratch` dir, or bash commands within script): we typically use `pip install -e {PDG package}` when creating an environment to run the PDG workflow. Will we use the `-e` option for this requirements file? That assumes that the user has cloned the PDG packages locally. The end-goal is to pass this workflow to other members of the ADC team, so we should consider not using `-e` and installing from GitHub repos instead. This would mean the main & develop branches of the repos will need to be merged so the main branch reflects all the features we have in develop before this requirements file will install exactly what we want.
  - this was resolved by creating a `pyproject.toml` file with the `poetry` package. See below comments for details.
- [ ] **2. at the beginning of the workflow, automate running script to transfer footprints from where they are stored on Delta to the `/tmp` dir on the node(s) running the job**
  - Currently the script `rsync_footprints_to_nodes.py` uses `rsync` to transfer the footprints from Kastan's dir to the `/tmp` folder on the node used for the job. Considering that Kastan will not be working on this project indefinitely, we should move this base dir to Robyn or Juliet's home dir, or some other persistent and neutral location accessible by all members of the allocation.
- [ ] **3. within the script or after the script to transfer the footprints, integrate a check for the transfer to be complete before moving onto the next step in the workflow**
  - Currently, we check `/tmp` folder size and number of files continuously in the terminal until the number stops changing.
- [ ] **4. Change all hard-coded file paths from `viz-workflow/utilities/IN_PROGRESS_VIZ_WORKFLOW.py` that are specific to a user, and hard-coded environment name from `viz-workflow/sbatch/BEST-v2_gpu_ray.slurm`**
  - such as `BASE_DIR_OF_INPUT` file path and output paths for staged files, rasters, etc.
  - make the output file paths change with each run so we avoid overwriting other files
- [ ]  **5. Optional: update the `@ray.remote` decorated functions in `viz-workflow/utilities/IN_PROGRESS_VIZ_WORKFLOW.py` to include Robyn's logging system used in the PDG packages**
- [ ] **6. Remove hard-coded private account name in the line `#SBATCH --account={ACCOUNT NAME}` within `viz-workflow/sbatch/BEST-v2_gpu_ray.slurm` so this file can be pushed  from GitHub without having to manually make sure that is removed first**
  - could do this with a source file for variable that represents the account name, and adding this source file to git ignore file
- [ ] **7. After staging, automate running `merge_staging()` to consolidate the staged files to one node**

**Comment by julietcohen** [comment]
Regarding #1, is a pre-made conda environment in a user's folder within `/scratch/{allocation ID}` able to be activated by other users? For example, if Robyn uses conda as her environment manager, can she run `conda activate /scratch/julietcohen/envs/pdgViz` in a terminal in her home dir and activate this environment to use for the ray workflow?

**Comment by mbjones** [comment]
@julietcohen this sounds great. I would recommend making the ray workflow be part of the viz-workflow package, and create the environment using poetry and package metadata, so when viz-workflow is installed, all of its dependencies will be met. This would be better than manually managing a separate requirements.txt file, and will follow our software release patterns. Happy to discuss how to get there if you'd like, but the basics are in the scalable computing course notes on building packages: https://learning.nceas.ucsb.edu/2022-09-arctic/sections/12-software-design-2.html

**Comment by julietcohen** [comment]
Thanks for the suggestion, Matt. I've been trying to wrap my head around using packages to install other packages. I'm confused about the difference between using `poetry` to create a package versus an environment. I'm also confused what you mean by making the `ray_workflow` branch a part of the` viz-workflow` package. I know I can install the `viz-workflow` (main branch) package from git. On the ray branch, I used poetry to create a new package called `install_ray_depend`) with the 5 necessary packages listed above as dependencies (added them to the file `~/viz-workflow/install_ray_depend/pyproject.toml`) but I cannot install that custom package by running `pip install -e viz-workflow/install_ray_depend`. So I think there is an important step missing in integrating the `ray_workflow` branch into the `viz-workflow` package.

**Comment by julietcohen** [comment]
I'm looking into using poetry in a different way: [initializing a pre-existing project](https://python-poetry.org/docs/basic-usage/#initialising-a-pre-existing-project) and [creating a virtual environment within the project's root dir](https://python-poetry.org/docs/configuration/#virtualenvsin-project)

**Comment by julietcohen** [comment]
## Using poetry

Created a stand alone `pyproject.toml` file within my local `viz-workflow` dir. Included requirements for python version 3.9 or greater but less than 4.0, main branches of `viz-staging`, `viz-raster`, & `viz-3dtiles`, `ray`, and `Glances`.

<details>
  <summary>pyproject.toml</summary>

```
[tool.poetry]
name = "viz-workflow"
version = "0.1.0"
description = "ray workflow for ice-wedge polygon dataset processing"
authors = ["Robyn Thiessen-Bock, Kastan Day, Matt Jones, Juliet Cohen"]
readme = "README.md"
packages = [{include = "viz_workflow"}]

[tool.poetry.dependencies]
python = "^3.9"
pdgstaging = {git = "https://github.com/PermafrostDiscoveryGateway/viz-staging.git"}
pdgraster = {git = "https://github.com/PermafrostDiscoveryGateway/viz-raster.git"}
ray = "2.2.0"
Glances = "^3.3.0.4"
viz-3dtiles = {git = "https://github.com/PermafrostDiscoveryGateway/viz-3dtiles.git"}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```
</details>

This file should be pushed to the main branch of `viz-workflow`. Also have to integrate the ray workflow into the package. **Does this just include pulling the necessary scripts from the `ray_workflow` branch into main?**

### Steps for user to activate a pre-configured environment for ray workflow:

- install python 3.9.*
- clone `viz-workflow` repo, `cd` into that dir
- activate pre-configured env by running `poetry shell`, which spawns a shell within the user's dir. Not sure if this should be done from base environment or a blank, new environment. It only worked for me from base. 
- then run `poetry install` ? Not sure if this is necessary after already running `poetry shell`. Documentation is [here](https://python-poetry.org/docs/basic-usage/#activating-the-virtual-environment), the relationship between the two commands is unclear to me.

**Comment by julietcohen** [comment]
## Using Poetry

After chatting with Matt about package structures, I was able to create a poetry package with the ray workflow dependencies.

Notes:
- Switched package manager from conda to venv on Delta. Conda did not seem to be compatible with poetry.
- Within my dir within `/scratch/`, I created a new venv environment `poetry_ray` and activated it.
- Within my home dir, I uninstalled and reinstalled poetry using the command `curl -sSL https://install.python-poetry.org | python3 -`
- Ran `poetry new viz-workflow` to create package skeleton, switched into that new dir, and populated the `.toml` file with all 5 dependencies.
- Ran `poetry shell`, which activates the poetry environment. In the terminal, this looks like:
`(viz-workflow-py3.9) (poetry_ray) [julietcohen@dt-login02 viz-workflow]$`
- Ran `poetry install` to install packages listed in the `.toml` file. This generated the `poetry.lock` file which should be added to the git repo when we do this for real after all PDG packages are finalized. I ensured this file does list all 5 ray workflow packages with their own dependencies as well.

With the intention of eventually including both the ray and parsl workflows within the `viz-workflow` package, Matt suggested the following package structure for `viz-workflow`:
<img width="201" alt="image" src="https://user-images.githubusercontent.com/88209596/210871817-c89fc892-3a73-483d-9b7b-05c72f35fdd6.png">

**Comment by julietcohen** [comment]
## Automate step to transfer footprints to nodes

This is the first step in the ray workflow, and the second step is to make manual edits to the slurm file and then run that. Perhaps these 2 steps (and potentially later steps in the workflow) can be automated by making all necessary edits to the slurm file at the very beginning, then using a py script to run the other scripts one by one with blocks between them that wait for the previous step to be complete, just as the parsl workflow is designed to do. The `subprocess` package and `Popen()` are used to generate processes in the terminal from a py script. The script can be blocked with the [`wait()`](https://docs.python.org/3/library/subprocess.html#subprocess.Popen.wait). If we want the workflow to periodically check if the process is still running and return a print or log statement if it is, we can use [`poll()`](https://docs.python.org/3/library/subprocess.html#subprocess.Popen.poll).

**Comment by julietcohen** [comment]
## MRE for queueing processes within script and providing updates

<details>
  <summary>use subprocess package</summary>

```python
import subprocess
from subprocess import Popen
import time

# define some processes that will be separated by a few seconds

# create subdir in home, for any delta user
username = subprocess.check_output("whoami").strip().decode("ascii")
cmd_1 = ['mkdir', f'/u/{username}/example_dir']
# generate file blank file in that new dir
cmd_2 = ['touch', f'/u/{username}/example_dir/example_file.txt']
# delete the dir and its contents
cmd_3 = ['rm', '-r', f'/u/{username}/example_dir']

# execute processes with seconds buffering them
# and include checks while they run

# ---------- PROCESS 1 ----------
process_1 = Popen(cmd_1)
check_process_1_initially = process_1.poll()
if check_process_1_initially is None:
    print('first check: process 1 is still running')
else:
    print('first check: process 2 is done')

time.sleep(3)

check_process_1_again = process_1.poll()
if check_process_1_again is None:
    print('second check: process 1 is still running')
else:
    print('second check: process 1 is done')

# ---------- PROCESS 2 ----------
process_2 = Popen(cmd_2)
check_process_2_initially = process_2.poll()
if check_process_2_initially is None:
    print('first check: process 2 is still running')
else:
    print('first check: process 2 is done')

time.sleep(3)

check_process_2_again = process_2.poll()
if check_process_2_again is None:
    print('second check: process 2 is still running')
else:
    print('second check: process 2 is done')

# ---------- PROCESS 3 ----------
process_3 = Popen(cmd_3)
check_process_3_initially = process_3.poll()
if check_process_3_initially is None:
    print('first check: process 3 is still running')
else:
    print('first check: process 3 is done')

time.sleep(3)

check_process_3_again = process_3.poll()
if check_process_3_again is None:
    print('second check: process 3 is still running')
else:
    print('second check: process 3 is done')

print('script finished')

```
</details>

**Comment by julietcohen** [comment]
## MRE for using `wait()` within script to insert blocks between processes, and `poll()` to provide updates

<details>
  <summary>use subprocess package</summary>

```python
from subprocess import Popen
import time

# sleep for 6 seconds for each command
cmd_1 = ['sleep', '6']
cmd_2 = ['sleep', '6']

# ---------- PROCESS 1 ----------
process_1 = Popen(cmd_1)

# wait for process 1 to be done before starting process 2
process_1.wait()

check_process_1 = process_1.poll()
if check_process_1 is None:
    print('process 1 is still running')
else:
    print('process 1 is done')
    # if wait() is working correctly, should print the process is done

# check if process 2 has been defined, should not be defined yet!
try:
    process_2
except NameError:
    # if variable does NOT yet exist
    print('process_2 has NOT yet been defined, `wait()` is indeed working as intended')
else:
    # if variable DOES exist
    print('process_2 has indeed been defined, `wait()` is NOT working as intended')

#if process_2:
#     print('process 2 has NOT yet been defined, `wait()` is indeed working as intended')
# else:
#     print('process 2 has indeed been defined, `wait()` is NOT working as indended')

# ---------- PROCESS 2 ----------
process_2 = Popen(cmd_2)

# wait for process 2 to be done before printing final statement of script
process_2.wait()

check_process_2 = process_2.poll()
if check_process_2 is None:
    print('process 2 is still running')
else:
    print('process 2 is done')
    # if wait() is working correctly, should print the process is done

print('script finished')

```
</details>

This is the best MRE I could come up with without adding too much complication. I tried using a couple commands for this MRE that print an output in the terminal after a set time interval rather than just sleeping for one time interval, but the `subprocess` package wants **only 1 command per process**, meaning that piping, or using `;` or using `&&` caused different behavior in the terminal process outputs than they would if they were just normally entered into the terminal. I also tried using the `watch` command and then killing the process after a defined amount of time with `timeout`, but turns out that the `wait()` function **specifically needs the running process to be successfully executed and completed, not killed.** Pretty interesting requirements, but they are fine for our purposes in the `rsync` command to transfer the footprints because that is just 1 command without those special characters. So I settled for the simple commands of sleeping for 6 seconds for this MRE, and clarifying that `process_2` has not been defined until `process_1` is all done! I think it does the job of demonstrating how `wait()` works.

**Comment by robyngit** [comment]
I'm going to close this issue for now because I think we're moving away from Ray. But there may still be relevant info in here @rushirajnenuji @alonakos

**Comment by alonakos** [comment]
Thank you @robyngit
